version: "3.8"
services:
  rabbitmq:
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  db:
    build:
      context: ./
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/.docker-conf/cs/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

networks:
 chat_network:
    driver: bridge

