version: "3.8"
services:
  rabbitmq:
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
        test: [ "CMD", "rabbitmqctl", "status" ]
        interval: 30s
        timeout: 10s
        retries: 5

  db:
    build:
      context: ./
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/.docker-conf/cs/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    ports:
      - '9010:9010'
    environment:
      - DB_HOST=host.docker.internal
      - RABBIT_HOST=host.docker.internal
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 100M
    networks:
      - chat_network
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

networks:
 chat_network:
    driver: bridge

